import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'profile',
  title: 'Profile',
  type: 'document',
  groups: [
    {name: 'human', title: 'Human-Authored'},
    {name: 'ai', title: 'AI-Derived'},
  ],
  fields: [
    // ============ HUMAN-AUTHORED ============
    defineField({
      name: 'name',
      title: 'Name',
      type: 'string',
      group: 'human',
      description: 'Profile identifier',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'values',
      title: 'Values',
      type: 'array',
      of: [{type: 'string'}],
      group: 'human',
      description: 'What you need from work. Agent 1 will not overwrite this.',
    }),
    defineField({
      name: 'dealBreakers',
      title: 'Deal Breakers',
      type: 'array',
      of: [{type: 'string'}],
      group: 'human',
      description: "Hard no's — triggers auto-reject in matching.",
    }),
    defineField({
      name: 'requirements',
      title: 'Requirements',
      type: 'array',
      of: [{type: 'string'}],
      group: 'human',
      description: 'Must-haves for any role.',
    }),
    defineField({
      name: 'voiceNotes',
      title: 'Voice Notes',
      type: 'object',
      group: 'human',
      description: 'Guidance for content generation',
      fields: [
        {
          name: 'tone',
          title: 'Tone',
          type: 'string',
          description: 'e.g., "Direct, Australian, metric-backed"',
          validation: (Rule) => Rule.required(),
        },
        {name: 'framing', title: 'Framing', type: 'string', description: 'e.g., "Pattern observer, systems thinker"'},
        {
          name: 'avoid',
          title: 'Avoid',
          type: 'array',
          of: [{type: 'string'}],
          description: 'e.g., ["corporate polish", "apologetic framing"]',
        },
      ],
    }),

    // ============ AI-DERIVED ============
    defineField({
      name: 'provenCapabilities',
      title: 'Proven Capabilities',
      type: 'array',
      group: 'ai',
      description: 'Generated by Agent 1 from project analysis.',
      of: [
        {
          type: 'object',
          fields: [
            {name: 'capability', title: 'Capability', type: 'string'},
            {
              name: 'strength',
              title: 'Strength',
              type: 'string',
              options: {
                list: [
                  {title: 'High', value: 'high'},
                  {title: 'Medium', value: 'medium'},
                  {title: 'Emerging', value: 'emerging'},
                ],
              },
            },
            {
              name: 'evidence',
              title: 'Evidence',
              type: 'array',
              of: [{type: 'string'}],
              description: 'Project references + metrics',
            },
            {
              name: 'themes',
              title: 'Themes',
              type: 'array',
              of: [{type: 'string'}],
              options: {layout: 'tags'},
            },
          ],
          preview: {
            select: {
              title: 'capability',
              subtitle: 'strength',
            },
          },
        },
      ],
    }),
    defineField({
      name: 'differentiators',
      title: 'Differentiators',
      type: 'array',
      of: [{type: 'string'}],
      group: 'ai',
      description: 'What sets you apart — AI-identified patterns.',
    }),
    defineField({
      name: 'growthEdges',
      title: 'Growth Edges',
      type: 'array',
      of: [{type: 'string'}],
      group: 'ai',
      description: 'Areas of interest with thinner evidence.',
    }),
    defineField({
      name: 'themesSummary',
      title: 'Themes Summary',
      type: 'text',
      rows: 3,
      group: 'ai',
      description: '2-3 sentence synthesis of patterns across projects.',
    }),
    defineField({
      name: 'lastAnalyzed',
      title: 'Last Analyzed',
      type: 'datetime',
      group: 'ai',
      description: 'Timestamp of last Agent 1 run.',
    }),
    defineField({
      name: 'sourceProjects',
      title: 'Source Projects',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'project'}]}],
      group: 'ai',
      description: 'Projects used in this analysis.',
    }),
  ],
  preview: {
    select: {
      title: 'name',
      lastAnalyzed: 'lastAnalyzed',
    },
    prepare({title, lastAnalyzed}) {
      return {
        title: title || 'Unnamed Profile',
        subtitle: lastAnalyzed
          ? `Analyzed: ${new Date(lastAnalyzed).toLocaleDateString()}`
          : 'Not yet analyzed',
      }
    },
  },
})
